### ISSUE TITLE
How can I change the image in the tab 

### ISSUE THREAD

**Issue by Harshpanday** [Hrishi1999/opPortfolio#7]
Hey, amazing portfolio.
I want to change the image that appears in the tab beside the title, I would be grateful if you could let me know how I can change that.
![tab](https://user-images.githubusercontent.com/48926152/223006172-5e5fc1a4-6b55-444b-9bee-317b87c5055d.jpg)

**Comment by Hrishi1999** [comment]
You can generate favicons using some online tool and place them in the `public` folder.
